//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MantenedoraCalidad.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONDICION_ENSAYO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CONDICION_ENSAYO()
        {
            this.PRUEBA = new HashSet<PRUEBA>();
        }
    
        public int id_condicion { get; set; }
        public float presion_gas { get; set; }
        public int poder_calorifico { get; set; }
        public float humed_relativa { get; set; }
        public float temp_ambiente { get; set; }
        public string cod_cocina { get; set; }
        public int id_gas { get; set; }
    
        public virtual COCINA COCINA { get; set; }
        public virtual TIPO_GAS TIPO_GAS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRUEBA> PRUEBA { get; set; }
    }
}
