//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MantenedoraCalidad.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ENSAYO_FUGA_G
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ENSAYO_FUGA_G()
        {
            this.PRUEBA = new HashSet<PRUEBA>();
        }
    
        public string id_fuga { get; set; }
        public bool est_conj_gas { get; set; }
        public bool est_indiv_gas { get; set; }
        public bool conexion { get; set; }
        public bool cumple_fuga_g { get; set; }
        public System.DateTime fecha_fug { get; set; }
        public System.TimeSpan hora_inicio_f { get; set; }
        public System.TimeSpan hora_termino_f { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRUEBA> PRUEBA { get; set; }
    }
}
