//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MantenedoraCalidad.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ENSAYO_COMB
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ENSAYO_COMB()
        {
            this.COMBU = new HashSet<COMBU>();
            this.PRUEBA = new HashSet<PRUEBA>();
        }
    
        public string id_combu { get; set; }
        public bool cumple_comb { get; set; }
        public System.DateTime fecha_ec { get; set; }
        public System.TimeSpan hora_inicio_c { get; set; }
        public System.TimeSpan hora_termino_c { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<COMBU> COMBU { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRUEBA> PRUEBA { get; set; }
    }
}
