//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MantenedoraCalidad.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ENSAYO_C_LLAMA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ENSAYO_C_LLAMA()
        {
            this.PRUEBA = new HashSet<PRUEBA>();
        }
    
        public string id_c_llama { get; set; }
        public Nullable<bool> disp_c_llama_f { get; set; }
        public bool disp_c_llama_c { get; set; }
        public bool encend_interc { get; set; }
        public bool cumple_control_llama { get; set; }
        public System.DateTime fecha_disp_llama { get; set; }
        public System.TimeSpan hora_inicio_dcl { get; set; }
        public System.TimeSpan hora_termino_dcl { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRUEBA> PRUEBA { get; set; }
    }
}
