//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MantenedoraCalidad.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ENSAYO_ELECTR
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ENSAYO_ELECTR()
        {
            this.PRUEBA = new HashSet<PRUEBA>();
        }
    
        public string id_electr { get; set; }
        public bool marc_instrucc { get; set; }
        public bool pr_part_activa { get; set; }
        public Nullable<float> potencia { get; set; }
        public Nullable<float> corriente { get; set; }
        public Nullable<float> continuidad { get; set; }
        public Nullable<float> aislamiento { get; set; }
        public Nullable<float> rig_dielect { get; set; }
        public bool cumple_v_numeric { get; set; }
        public bool cumple_electr { get; set; }
        public System.DateTime fecha_electr { get; set; }
        public System.TimeSpan hora_inicio_e { get; set; }
        public System.TimeSpan hora_termino_e { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRUEBA> PRUEBA { get; set; }
    }
}
