//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MantenedoraCalidad.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EQUIPO_PRUEBA
    {
        public int id_instrum { get; set; }
        public string nom_instrum { get; set; }
        public string marca_instrum { get; set; }
        public string modelo_instrum { get; set; }
        public double correc_calibrac { get; set; }
        public System.DateTime fecha_ven_calib { get; set; }
        public string unidad_med_instrum { get; set; }
    }
}
