//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MantenedoraCalidad.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class INFORME_PRUEBA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public INFORME_PRUEBA()
        {
            this.PRUEBA = new HashSet<PRUEBA>();
        }
    
        public string n_planilla { get; set; }
        public System.DateTime fecha_docum { get; set; }
        public string observacion { get; set; }
        public string nota { get; set; }
        public byte[] foto_1 { get; set; }
        public byte[] foto_2 { get; set; }
        public byte[] foto_3 { get; set; }
        public string rut_usuario { get; set; }
    
        public virtual USUARIO USUARIO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRUEBA> PRUEBA { get; set; }
    }
}
