//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MantenedoraCalidad.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERMISO
    {
        public int id_permiso { get; set; }
        public bool lectura { get; set; }
        public bool escritura { get; set; }
        public bool modificacion { get; set; }
        public bool eliminacion { get; set; }
        public int id_rol { get; set; }
        public int id_ventana { get; set; }
    
        public virtual ROL ROL { get; set; }
        public virtual VENTANA VENTANA { get; set; }
    }
}
