//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MantenedoraCalidad.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public USUARIO()
        {
            this.INFORME_PRUEBA = new HashSet<INFORME_PRUEBA>();
        }
    
        public string rut_usuario { get; set; }
        public string nom_usuario { get; set; }
        public string apell_usuario { get; set; }
        public string contr_usuario { get; set; }
        public string nom_supervisor { get; set; }
        public int id_rol { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INFORME_PRUEBA> INFORME_PRUEBA { get; set; }
        public virtual ROL ROL { get; set; }
    }
}
